style-css-ui E-shop
st-hoangle/FE-Internship-2021_Hoang-Le_FE-Exercise pull request #13
Opened 2021-04-23 09:06 UTC by st-hoangle

## Overview 
- [x] Create folder structure
- [x] Styles css e-shop

2021-04-23 10:08 UTC, st-dungnguyen requested changes

2021-04-23 10:08 UTC, st-dungnguyen commented on exercise_e_shop/home.html
> +        <p class="text-center uppercase">design by iceo.co - &copy; 2019. all rights reserved.</p>
`uppercase` -> `text-uppercase`

2021-04-23 10:08 UTC, st-dungnguyen commented on exercise_e_shop/home.html
>        <div class="footer-copyright">
`footer-copyright` -> `copyright`

2021-04-23 10:08 UTC, st-dungnguyen commented on exercise_e_shop/home.html
>                <button class="btn btn-white uppercase">view all</button>
`uppercase` -> `text-uppercase`

2021-04-23 10:10 UTC, st-dungnguyen requested changes

2021-04-23 10:10 UTC, st-dungnguyen commented on exercise_e_shop/assets/styles/base/_font.scss
> +
File rỗng ??? Xác định lại nội dung cần tách, không để file rỗng

2021-04-25 15:33 UTC, st-dieple commented on exercise_e_shop/assets/styles/base/_mixins.scss
> +@mixin colrespon($colMax, $screen-size) {
Đặt tên mixin rõ ràng

2021-04-25 15:33 UTC, st-dieple commented on exercise_e_shop/assets/styles/base/_variable.scss
> +$color-organ: #fbb03b;
đăt tên biến, class rõ ràng, ưu tiên tìm tên gắn gọn phù hợp, ko nên viết tắt

2021-04-25 15:33 UTC, st-dieple commented on exercise_e_shop/assets/styles/base/_variable.scss
> +$sm: 576px;
Đặt tên biến rõ ràng. Nên gộp chung vào `breakpoint`

2021-04-25 15:33 UTC, st-dieple commented on exercise_e_shop/assets/styles/layout/_footer.scss
> +footer {
Các class liên quan trực tiếp đến footer phải dk style bên trong footer

2021-04-25 15:33 UTC, st-dieple commented on exercise_e_shop/assets/styles/layout/_header.scss
> +@import "../base/all";
Ko cần import ở đây

2021-04-26 06:40 UTC, merged