e shop card event card
st-hoangle/FE-Internship-2021_Hoang-Le_FE-Exercise pull request #20
Opened 2021-05-05 04:40 UTC by st-hoangle

#Overview
- show the cart to the screen
- Calculate the total cost of the product
- event for cart
- 
![image](https://user-images.githubusercontent.com/82007436/117097709-9287b900-ad96-11eb-8514-617a0e3682d9.png)

2021-05-05 10:38 UTC, st-dungnguyen commented
@st-hoangle header đè mất cart

2021-05-05 17:05 UTC, st-dungnguyen requested changes

2021-05-05 17:05 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/cart.js
> +  var products = JSON.parse(localStorage.getItem('listproduct'));
@st-hoangle Em định nghĩa hàm fetchData() để return lại mảng product (Nếu có api thì hàm này sẽ dùng để gọi api và return về mảng product). Sau đó viết hàm render(data) hoặc load(data) để hiện thị ra ngoài view.

```js
// khai báo mảng product
var product = [...]

// fetch dữ liệu
function fetchData(){...};

// đổ dữ liệu ra view
function render(data){...};

// gọi hàm để sử dụng
var data = fetchData();
render(data):
```
Tương tự tách các hàm xử lý sự kiện để có thể tái sử dụng

2021-05-05 17:05 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/showCart.js
> +var listProductCart = JSON.parse(localStorage.getItem('listProductCart'));
tương tự tách thành các hàm rõ ràng về chức năng và có thể tái sử dụng

2021-05-07 01:48 UTC, st-dungnguyen requested changes

2021-05-07 01:48 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/addTocart.js
> +  if (listCart == null) {
`if(listCart)` is enough. 
Read more about`falsy` values: https://developer.mozilla.org/en-US/docs/Glossary/Falsy

2021-05-07 01:48 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/addTocart.js
> +  for (i = 0; i < listCart.length; i++) {
Không cần tìm index nếu nó chưa có trong giỏ hàng. Cho nên quăng vào trong if

2021-05-07 01:48 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/cart.js
> +  render(data);
lỗi indent

2021-05-07 01:48 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/showCart.js
> +    // console.log(productCode);
code dư thừa nên xoá

2021-05-07 01:48 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/showCart.js
> +  document.getElementsByClassName('cart-btn-quantity')[0].innerHTML = listCart.length;
code dưới reload() có chạy không? Và có cần chạy gì sau khi reload() không?

2021-05-07 02:34 UTC, st-dungnguyen requested changes

2021-05-07 02:34 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/showCart.js
> +  setDataLocal('count', listCart.length);
@st-hoangle Những đoạn code dưới reload() có chạy không? Hỏi lần 2

2021-05-07 02:34 UTC, st-dungnguyen commented on exercise_e_shop/assets/js/showCart.js
> +var listProductCart = getDataLocal('listProductCart');
Vị trí khai báo hàm và sử dụng hàm lộn xộn.

2021-05-07 02:39 UTC, st-hoangle commented on exercise_e_shop/assets/js/showCart.js
> +  setDataLocal('count', listCart.length);
có a nhá cái này mỗi lần reload nó cần set lại trên local..

2021-05-07 09:04 UTC, merged