design layout
st-hoangle/FE-Internship-2021_Hoang-Le_FE-Exercise pull request #3
Opened 2021-04-08 02:30 UTC by st-hoangle

- Description
  + Tạo file tài liệu html, dựng layout cho trang .
  + Đặt tên class cho các thẻ (chỉ đặt tên class, không cần phải style theo design)
-reference
 + https://www.figma.com/file/tfJMAAtI0zSsCKqAaxweFo/Ecommerce-Shopping---HomeScreen

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +
ko cần empty line ở đây

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +
ko cần empty line ở đây

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +          <a href="">
ko để trong href, ko có link thì thay bằng `#`

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +        <div class="category">
menu nên nằm trong `header-center`

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +          <img class="header-category" src="./Svg/category.svg" alt="">
ko để trong alt text

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +            <li><a>Clothing & Shoes</a></li>
thẻ a phải luôn có href -> nếu chưa có link thì: `href="#"` như comment ở trên
Kiểm tra cho các thẻ a khác

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +      <div class="formSearch">
tên class nên đặt theo kiểu aa-bb-cc, không nên đặt theo camel, để phân biệt với thuộc tính name hoặc các biến khi sử dụng trong javascript
sửa và kiểm tra lại các class bị lỗi tương tự

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +      <div class="style-header-right">
đồng nhất các tên class.
Phía trên là `header-left` thì ở đây sẽ là `header-right`

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +          <i></i>
Ko để thẻ trống

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +        <div class="container">
tham khảo comment: https://github.com/st-linhdoan/FE-Internship-2021_Linh-Doan-T-B_FE-Exercise/pull/4#discussion_r609881431

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +          <img class="banner" src="./image/image 1.png" alt="SuperSale">
alt nên cách ra đúng chữ `Super sale`

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +      <section class="toolbar">
ở đây ko phải là section `toolbar`, toolbar chỉ là 1 phần trong list product

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +        <div>
Đặt class cho thẻ div

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +            <select class="styles-elect" name="" id="">
1. Thêm gia trị cho các attribute name, id
    Tham khảo: https://github.com/st-linhdoan/FE-Internship-2021_Linh-Doan-T-B_FE-Exercise/pull/4#discussion_r609895063

2. Ko dùng `style` trong tên class, đặt tên class theo đúng vai trò của thẻ

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +            <div class="">
Đặt class cho thẻ

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +            <li>
đặt class cho `<li>`

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +                <img src="./image/Image.png">
Thêm alt text

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +                  <p class="product-List-name">Vintage Typewriter to post awesome stories about UI design and
1. ko cần viết hoa cho class
2. class không đúng ý nghĩa: tên của product, chớ ko phải tên của product list 
Kiểm tra lại các class khác 😉

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +                <img src="./image/Image(2).png">
Tham khảo: https://github.com/st-linhdoan/FE-Internship-2021_Linh-Doan-T-B_FE-Exercise/pull/4#discussion_r609888090

2021-04-08 17:50 UTC, st-dieple commented on exersice_html/home.html
> +    <div style="text-align: center;" class="container">
không dùng style inline

2021-04-09 06:55 UTC, st-dungnguyen commented on exersice_html/home.html
> +      <div>
thẻ `<div>` chỗ này dùng làm gì?

2021-04-09 06:55 UTC, st-dungnguyen commented on exersice_html/home.html
> +      <section>
đặt tên class cho section

2021-04-09 07:07 UTC, st-hoangle commented on exersice_html/home.html
> +      <div>
chổ thẻ div này e quên chưa đặt class. e nghĩ cần một thẻ div lớn trong cái container để e chỉnh css sử dụng cái display:flex nên e bỏ thẻ div ở đó á a.

2021-04-09 08:07 UTC, st-dieple commented
LGTM!

2021-04-09 09:17 UTC, st-dungnguyen requested changes

2021-04-09 09:17 UTC, st-dungnguyen commented on exersice_html/home.html
> +                <img src="./image/image-6.png" Vintage Typewriter>
thiếu alt

2021-04-09 09:17 UTC, st-dungnguyen commented on exersice_html/home.html
> +                <img src="./image/image-7.png" Vintage Typewriter>
như trên

2021-04-09 09:17 UTC, st-dungnguyen commented on exersice_html/home.html
> +                <img src="./image/image-8.png" Vintage Typewriter>
Fix luôn cho mấy chỗ khác

2021-04-09 09:17 UTC, st-dungnguyen commented on exersice_html/home.html
> +    <div class="container">
footer có design khác với header và main nên không dùng container

2021-04-12 01:20 UTC, st-dungnguyen requested changes

2021-04-12 01:20 UTC, st-dungnguyen commented on exersice_html/home.html
> +              <img src="./image/image-2.png">
thiếu `alt`

2021-04-12 01:20 UTC, st-dungnguyen commented on exersice_html/home.html
> +            <a href="#" alt="Lee Pucker design">
`alt` cho a?

2021-04-12 01:20 UTC, st-dungnguyen commented on exersice_html/home.html
> +            <a href="#" alt="Lee Pucker design">
Như trên và lặp nhiều bên dưới

2021-04-12 01:20 UTC, st-dungnguyen commented on exersice_html/home.html
> +              <img src="./image/image-11.png" Vintage Typewriter>
thiếu `alt` kiểm tra lại các thẻ `img`, bị rất nhiều

2021-04-12 07:30 UTC, closed without merging